//处理js资源，因为webpack只能处理模块化语法，并不能编译其他高级的js语法，为了防止有的浏览器不能兼容高级语法需要使用webpack中的babel编译成低版本的语法
//需要代码检查和代码规范约束，需要使用eslint插件
//说一下eslint，vscode里下载的eslint第三方插件是用来在写代码时检查提示代码错误的，如果没有它那么只有等到编译时才知道代码错误，而编译时提示的代码规范错误所遵循的是.eslintrc.js中设定的约束规则，如果使用了eslint第三方插件那么它也是根据这个文件来提示代码错误的。而默认清空下这个插件会按照.rc文件的规则检查所有代码的规范，我们只希望它检查src目录下的所以需要eslintignore文件忽略其他目录
//配合prettier使用，VScode中安装第三方插件prettier,然后设置它为默认格式化程序，并在vscode设置中设置保存时自动格式化即可，如果需要配置格式化的规则，那么可以通过.prettierrc文件
let a = 10
console.log(a)
var b = 99
console.log(b)
